FROM nginx
COPY . .

RUN apt-get update -y \
    && apt-get install -y curl \
    && apt-get install -y bzip2 \
    && curl -o /usr/local/bin/n https://raw.githubusercontent.com/visionmedia/n/master/bin/n \
    && chmod +x /usr/local/bin/n \
    && n 6.11.5 
RUN npm install \
    && npm run build \
    && mv dist/* /usr/share/nginx/html
